`timescale 1ns / 1ps

/**
 * Module: system_bus
 * Description: Implements Memory-Mapped I/O (MMIO) and address decoding.
 * It routes the CPU's address and data signals to the correct peripheral 
 * based on the requested memory address.
 */
module system_bus(
    // CPU Interface
    input  logic [15:0] proc_addr,        // Address generated by the CPU
    input  logic [15:0] proc_data_out,    // Data from CPU to peripherals (Store)
    input  logic        proc_mem_w_en,    // Write enable signal from CPU
    output logic [15:0] proc_data_in,     // Data from peripherals to CPU (Load)
    
    // RAM Interface (0x0000 - 0x7FFF)
    output logic [15:0] ram_addr,         // Address routed to General RAM
    output logic [15:0] ram_data_out,     // Data routed to General RAM
    output logic        ram_w_en,         // Write enable for General RAM
    input  logic [15:0] ram_data_in,      // Data read from General RAM
    
    // VGA Controller Interface (0x8000 - 0x8FFF)
    output logic [15:0] vga_addr,         // Address routed to Video RAM
    output logic [15:0] vga_data,         // Pixel data routed to Video RAM
    output logic        vga_w_en,         // Write enable for Video RAM
    
    // Input Controller Interface (0xF000)
    input  logic [15:0] buttons_data      // Buffered button data from Input Controller
    );
    
    /**
     * Address Decoding Logic:
     * Defines the memory map of the system. Each peripheral is assigned 
     * a specific address range.
     */
    always_comb begin
        // Default values to prevent latches and floating signals
        proc_data_in = 16'd0;
        
        ram_addr = 16'd0;
        ram_data_out = 16'd0;
        ram_w_en = 1'b0;
        
        vga_addr = 16'd0;
        vga_data = 16'd0;
        vga_w_en = 1'b0;
        
        // --- ADDRESS DECODING TABLE ---
        
        if(proc_addr < 16'h8000) begin 
            // Range: 0x0000 to 0x7FFF (32KB) => General Purpose Data RAM
            ram_addr = proc_addr;
            ram_data_out = proc_data_out;
            ram_w_en = proc_mem_w_en;
            proc_data_in = ram_data_in;    
        end
        else if(proc_addr >= 16'h8000 && proc_addr <= 16'h8FFF) begin
            // Range: 0x8000 to 0x8FFF (4KB) => Video RAM (VRAM)
            // Note: The VGA controller uses 0 to 1199 for the 40x30 grid.
            vga_addr = proc_addr;
            vga_data = proc_data_out;
            vga_w_en = proc_mem_w_en;
        end
        else if(proc_addr == 16'hF000) begin
            // Address: 0xF000 => Input Device Port (Button FIFO)
            proc_data_in = buttons_data;
        end
    end
    
endmodule